### ISSUE TITLE
Stable release with most recent translations

### ISSUE THREAD

**Issue by dunxd** [mikespub-org/seblucas-cops#104]
@mikespub I noticed a few translations (from @horus68 - #99, #100, #103) were commited and merged into `main` after the announcement of 2.8.1, but the next release that includes them is a release candidate with breaking changes.

Any chance of pushing out a release with all the most recent translations but none of the breaking changes mentioned in 3.x release notes? Maybe make 2.8.2 a release? 

I'd like to do a release of HA COPS with those translations as they relate to 2.8.1.

**Comment by mikespub** [comment]
Oops - those were actually merged as part of [tag 2.8.2](https://github.com/mikespub-org/seblucas-cops/releases/tag/2.8.2) already.

Do you need me to make a special release for that on Github, or is the tag enough to get you started?

**Comment by dunxd** [comment]
Release would be handy for me since I still haven't got my head around
composer, but probably also helpful to have a complete final release in
version 2.x for anyone that has trouble with 3.x for any reason.

**Comment by mikespub** [comment]
Hi @dunxd

if you're looking for stability with a PHP 8.1 version you'd be better off using [release 2.8.1](https://github.com/mikespub-org/seblucas-cops/releases/tag/2.8.1) instead of tag 2.8.2

And if you want to include the translation PRs from @horus68 , the 'extra.files' change can be found in https://github.com/mikespub-org/seblucas-cops/pull/103/files

The work I did afterwards already introduced some changes in preparation of the 3.x version, so if PHP 8.2 isn't a problem you'd be better off using release 3.1.2 instead of tag 2.8.2. That's one of the reasons I didn't make an "official" release of it :-)

Note: for 3.1.x if you're using the built-in PHP server in HA COPS [run.sh](https://github.com/dunxd/HomeAssistantAddons/blob/main/COPS/run.sh) you'll want to try the `router.php` script:

```php
php -S 0.0.0.0:8000 router.php
```
Let me know if you have any issues with the HA COPS setup there

**Comment by dunxd** [comment]
HA COPS runs in a docker container  based on Alpine Linux. It installs PHP without specifying a version so I'll need to check what version is currently being installed.

I do run using the built in PHP server as it is small and well suited to a small install. Thanks for the heads up about the script. I'll do some testing and see if 3.1.x is the way to go for this.

**Comment by dunxd** [comment]
I've gone ahead and released a version of HA COPS using 3.1.3.  I fixed some issues with the bootstrap5 template and added in the series and title sections to the author page.

**Comment by mikespub** [comment]
Thanks @dunxd - closing this issue for now
