### ISSUE TITLE
Mail from 3.1.1 does not work (2.6.1 works)

### ISSUE THREAD

**Issue by marioscube** [mikespub-org/seblucas-cops#105]
I updated to version 3.1.1.

Copied the relevant portion of the config file from 2.6.1 and tried to email a book.

I get : 
![Screenshot 2024-09-12 at 15 02 35](https://github.com/user-attachments/assets/a2d86742-c4c5-427e-ad2a-f62323649925)

On 2.6.1 from same PC and browser:
![Screenshot 2024-09-12 at 15 03 22](https://github.com/user-attachments/assets/d00a57fd-1adb-4e07-8868-83b5832ffaff)

Did I miss something to configure?

**Comment by mikespub** [comment]
Hi @marioscube

hmm, I had a similar error message once when I used client-side render and I didn't clear my browser cache between switching versions, but I never managed to reproduce it afterwards.

Can you try again after clearing the cache and doing a full page reload? If it happens again I'd be very interested in knowing more...

**Comment by marioscube** [comment]
@mikespub 

Tried again with 2 different browsers (firefox & orion) on private mode.
Caches were cleared.
Nothing changed from the default config regarding client-side render.
 
The only thing that is retained in the cache is the e-mail address (I don't like that, but that's another issue).

Same "message" [object Object].

Does your version work?

**Comment by marioscube** [comment]
Error: (Debian12 apache2)

[Thu Sep 12 15:45:38.780732 2024] [php:notice] [pid 444481:tid 444481] [client 192.168.1.190:51332] Invalid COPS request path '/index.php/mail', referer: http://192.168.1.120/slcops/index.php/recent?db=1

**Comment by mikespub** [comment]
Hi @marioscube good news: I managed to reproduce the problem

There were a couple of issues:
1. in util.js it doesn't take into account the baseurl and posts to index.php/mail regardless of where you are, e.g. in /cops/index.php/books/17/Lewis_Carroll/Alice's_Adventures_in_Wonderland. So that gets sent to the wrong URL, and returns something it doesn't understand
2. in MailHandler() if there actually is an error, it returns an HTML error instead of a plain-text message, which again is not handled correctly

I'll submit a fix for both shortly - thanks for catching this...

**Comment by marioscube** [comment]
@mikespub 

Glad to be able to help out!

Thank you (and Seb Lucas) for COPS!

**Comment by marioscube** [comment]
@mikespub 

Fix confirmed working!

**Comment by mikespub** [comment]
Excellent, thanks 👍
