### ISSUE TITLE
Please support PHP 7.4

### ISSUE THREAD

**Issue by hgy59** [mikespub-org/seblucas-cops#17]
It is boring.
You write that PHP 8 is required and at least PHP 8.1 is recommended.
And in the Changelog is not clear at which version of cops which PHP versions are supported.

We are providing packages for Synology NAS and a lot of models do not support PHP 8.1.
In https://github.com/SynoCommunity/spksrc/pull/5817 we are upgrading to cops 1.3.6.
This version runs with PHP 7.4 (at least I did not find any problems related to PHP version).

Can you please provide information which versions of cops can run with PHP 7.4?

**Comment by mikespub** [comment]
Hi @hgy59  I do have a Synology NAS (which is partly how I ended up here), and I used the SynoCommunity package to install COPS in the early days too - thanks for that :-)

Now to be fair, the original releases at https://github.com/seblucas/cops still mostly work with PHP 7.4 which is why it wasn't really a focus for me here. But I didn't take into account the possibility that someone would want to support both 7.4 and 8.x with the same release.

As you've discovered, the 1.2.x releases were mainly about fixing the immediately incompatibility issues for PHP 8.x, and the 1.3.x releases were about integrating some long-pending PRs and updates. So you're right that the 1.3.6 release should work with PHP 7.4 as far as I know...

With the 1.4.x releases, I never intentionally chose to break PHP 7.4 compatibility, but I may have added some typing hints here & there that didn't exist before 8.0, and I may not always have kept them in the phpdoc section. If so, changing back to a code base that's compatible to both 7.4 and 8.x shouldn't be too hard to do at this stage. I'll keep that in mind when I prepare the 1.4.2 release, but I'm still moving pieces around at the moment, so it's not stabilized yet.

I don't have anything in mind for future 1.5.x releases yet, but so far I don't see why we couldn't maintain 7.4 compatibility a while longer...

**Comment by hgy59** [comment]
@mikespub thanks for claryfication.
Currently it is enough for me to know that COPS 1.3.6 still should work with PHP 7.4.

BTW, there is the file `checkconfig.php` that checks for PHP >= 5.3, but I am not sure, whether this file is executed anymore.
and another hint: my findings are, that for viewing epub files the php extension `zlib` is required, but this isn't documented.

**Comment by mikespub** [comment]
I've downgraded the current code base to PHP 7.4 with rector, and there were indeed a few types, match and str_* functions that were incompatible.

About the zlib extension, good catch - that's actually mentioned in the [resources/tbszip/README.md](/mikespub-org/seblucas-cops/blob/main/resources/tbszip/README.md) file, but I hadn't seen the issue since most distributions include it now.

The checkconfig.php file could certainly use a refresh at some point though :-)

**Comment by mikespub** [comment]
Included in release 1.4.2 at https://github.com/mikespub-org/seblucas-cops
