### ISSUE TITLE
Author name link missing from books list

### ISSUE THREAD

**Issue by dunxd** [mikespub-org/seblucas-cops#25]
On the book detail page, each author name is a link I can click to see a page showing books by that author.  The template variable for this (`author.url`) is missing on the books list page (but series gets `seriesurl`).  I guess this is because a book might have multiple authors, but only one series. 

Anyway, it would be nice to be able to select an author from the books list page. 

Something needs changing in JSON_renderer.php - there are two functions to get the book data - `getBookContentArray` and `getFullBookContentArray`. First is used for books list page, second is used for book details page. First doesn't have authors URL second does. It looks like the first just gets a single string containing all the authors names, whereas the second creates an array with all the authors in.  I'm not sure the rationale between having two different functions that work so differently - guess it is a performance thing?

**Comment by mikespub** [comment]
There's probably some optimizations that could be made, but yes, I believe historically the idea was that getBookContentArray would only grab the information people would like to see in book lists, while getFullBookContentArray grabs about everything for 1 book.

If you do this for 50-100 or more books at a time, this could become a bit heavy on smaller platforms - not to mention quite inefficient :-)

On the other hand, since the authors are already collected for the book list anyway, there's no reason why we couldn't provide the author details incl. the link as an extra template variable in getBookContentArray too if you want.

**Comment by mikespub** [comment]
Actually as it is today, COPS seems to query about the same information regardless of whether it's for booklists or for individual books in JSON_renderer, so there's definitely room for improvement. I'll see what I can do...

**Comment by mikespub** [comment]
You can now loop over entry.book.authors in main.html the same way you can for it.book.authors in bookdetail.html

**Comment by dunxd** [comment]
Great - this works:

```
{{~ entry.book.authors:author:author_index}}
  <a href="{{=author.url}}">{{=htmlspecialchars (author.name)}}</a>
{{~}}
```
Need to sort out the separator logic.

**Comment by mikespub** [comment]
Included in [release 1.4.4](https://github.com/mikespub-org/seblucas-cops/releases/tag/1.4.4)

**Comment by dunxd** [comment]
The changes that you made in above commits seem to be missing from release 2.0.1 and current state of main branch - so bootstrap5 no longer works server side.

**Comment by dunxd** [comment]
This doesn't work server side.  I'm getting an error:

```
Undefined constant "author_index" in $out = 
```
Which is likely getting triggered by the iteration at https://github.com/mikespub-org/seblucas-cops/blob/2ae0112eb5dcebc99d98a2833497651de65a75c6/templates/bootstrap5/main.html#L47

I seem to recall that there was an issue with index names with dot.php?
