### ISSUE TITLE
Feed.php Broken in 1.4.3+ - Only SHows "Recent additions"

### ISSUE THREAD

**Issue by Chirishman** [mikespub-org/seblucas-cops#27]
Something that changed in 1.4.3 and 1.4.3b has resulted in feed.php only showing `Recent additions` category when browsed in my OPDS reader app (Kybook3)

Reverting to a 1.4.2 returns the other categories.

On 1.4.2:
![IMG_7953](https://github.com/mikespub-org/seblucas-cops/assets/7658840/32ab9c16-ce3d-459b-b0d6-8f165deda038)

On 1.4.3 and 1.4.3b:
![IMG_7954](https://github.com/mikespub-org/seblucas-cops/assets/7658840/fb4c1e4f-2a79-4b2f-8359-938c6a96a8f9)

I do have a `cops_ignored_categories` value but it only contains `language`
```php
$config['cops_ignored_categories'] = array("language");
```

**Comment by mikespub** [comment]
It seems Kybook3 may have the same problem as koreader in not dealing very well with OPDS feeds containing link rel="..." relations other than a few hard-coded ones (even though the OPDS specs recommends using them).

See https://github.com/mikespub-org/seblucas-cops/issues/26 for a quick fix, or get the latest version from source - I switched back to using "subsection" instead of "section" for those top-level links.

**Comment by mikespub** [comment]
Included in [release 1.4.4](https://github.com/mikespub-org/seblucas-cops/releases/tag/1.4.4)

Let us know if you have any more issues with certain OPDS links on Kybook3

**Comment by Chirishman** [comment]
So the previous no-categories behavior has stopped but I'm seeing a new odd thing now:

![image](https://github.com/mikespub-org/seblucas-cops/assets/7658840/cf4d8aa5-c445-4e18-b9d4-e2a63fdf39ed)

![image](https://github.com/mikespub-org/seblucas-cops/assets/7658840/db60cae1-f1c9-4cf5-b759-f48e6f454a63)

Other tags and metadata items are being listed at the top of the view before any books get listed.

Also on a possibly related or possibly unrelated note I have noticed that I am no longer being offered m4b downloads of books.

**Comment by mikespub** [comment]
These are extra sorting & filtering options that will show up in OPDS feeds for "modern" e-readers that support facets: https://specs.opds.io/opds-1.2.html#4-facets

You can disable these options in your config_local.php by setting:

```
/*
 * Show links to filter by Author, Language, Publisher, Rating, Serie or Tag in OPDS catalog (using facets)
 * Note: this will only work if your e-reader supports facets in OPDS feeds, like Thorium Reader for example
 * See https://specs.opds.io/opds-1.2.html#4-facets for specification details
 *
 * Available values: ['author', 'language', 'publisher', 'rating', 'series', 'tag']
 */
// $config['cops_opds_filter_links'] = ['author', 'language', 'rating', 'tag'];
$config['cops_opds_filter_links'] = [];
```

I'll double-check if sorting links are also disabled then, otherwise I may have to add another setting there...

Regarding m4b formats, the list of preferred formats can also be changed in config_local.php:

```
/*
 * Prefered format for HTML catalog
 * The two first will be displayed in book entries
 * The other only appear in book detail
 */
$config['cops_prefered_format'] = ['EPUB', 'PDF', 'AZW3', 'AZW', 'MOBI', 'CBR', 'CBZ'];
```

I'm not sure how the m4b format shows up in Calibre - probably you need to add 'M4B' in the list here?

**Comment by mikespub** [comment]
Sort links are now optional too in [release 1.4.5](https://github.com/mikespub-org/seblucas-cops/releases/tag/1.4.5)

You'll need to update your config_local.php if you want to disable them, like for the filter links above

**Comment by Chirishman** [comment]
> I'm not sure how the m4b format shows up in Calibre - probably you need to add 'M4B' in the list here?

I'll try that but I do know it wasn't necessary on the prior fork. It's an audiobook format and it had been being picked up succesfully previously.

It's not a burning issue for me since I actually primarily serve my audiobooks to myself using a [Plex](https://plex.tv/) library and the [Prologue app](https://prologue.audio/) as a specialized client but I ran into it when I set a friend up with access to my COPS library the other day and directed them to click on a book that I *only* had in calibre as an M4B at that time and it behaved as if there were no formats available to download at all.

FYI M4B is a fun format and it's [not that hard](https://blog.chiriserv.org/Advanced-Audiobook-Generation/) to convert your old mp3 or cd audiobooks into a proper M4B with a table of contents and chapters etc

> Sort links are now optional too in [release 1.4.5](https://github.com/mikespub-org/seblucas-cops/releases/tag/1.4.5)
> 
> You'll need to update your config_local.php if you want to disable them, like for the filter links above

Noted! Implementing that now...

**Comment by Chirishman** [comment]
1.4.5 plus the new setting fixes the clutter issue I was seeing, but the `cops_prefered_format` setting hasn't fixed the lack of support for m4b files.

I think it may have to do with `Data.php` which has seen a ton of changes since seblucas' version. In particular I noticed there's no listing for m4b in the mimetype array, though there is for m4a. https://github.com/mikespub-org/seblucas-cops/blob/d06ad8d28b3bace8e5f238a38c729a4a36fe7ec3/lib/Calibre/Data.php#L43

**Comment by mikespub** [comment]
Glad to hear the config options fixed the clutter for you :-)

About the support for m4b, we may have to dig a little deeper, because I haven't really touched the core functionality in Data.php since seblucas' version. Lots of re-shuffling and cosmetic stuff, but not at the core...

For instance, there wasn't an m4b entry in the mimetypes before, and there still isn't one.

From the logic flow of COPS, this is roughly what happens:
1. you navigate to a page where you get a list of books from Calibre\BookList - no restriction on format
2. for each of the books, we create a book instance in Calibre\Book - no restriction on format
3. for each book instance, we get the entry to send back via JSON - no restriction on format
4. for each book entry, get a link array with the authors, series and data (=actual files) by book in Calibre\Book
   - only the $config['cops_ignored_formats'] are ignored in the database lookup in Calibre\Book
   - but then we check if the data is a known type in Calibre\Data

Here it gets tricky, because we check the format (extension) against the mimetypes. Are you sure you didn't have a customized mimetypes table with 'm4b' added, or does the Calibre database contain 'M4A' for the format field of the data table?

```
$ sqlite3 metadata.db
sqlite> select id, book, format, name from data;
1|2|EPUB|The Return of Sherlock Holmes - Arthur Conan Doyle
2|3|EPUB|The Casebook of Sherlock Holmes - Arthur Conan Doyle
...
sqlite> .quit
```
Is this something you could check? Do we actually get a link for the m4b file at this point or not?

Because the next step is in JSON renderer (HTML page) or OPDS renderer (OPDS feed), where we do some more processing of the formats:

5. in OPDS renderer, for each book entry, render the links found in step 4 - no change compared to before
5. in JSON renderer, for each book entry, go through the list of $config['cops_preferred_formats'] and get the data for the first 2 ones it finds
  - if 'M4A' (or whatever above) is not in your config_local.php then it won't show up...

When you go to an individual book in the HTML page, the logic flow is slightly different, and the filtering of formats at well. There you should get a link to all data formats it found in step 4.a. above, regardless of the extension.

And yes, all this has been a bit of a mess even in seblucas' version :-)
