### ISSUE TITLE
Support for m4b files in COPS

### ISSUE THREAD

**Issue by mikespub** [mikespub-org/seblucas-cops#28]
@Chirishman

About the support for m4b, we may have to dig a little deeper, because I haven't really touched the core functionality in Data.php since seblucas' version. Lots of re-shuffling and cosmetic stuff, but not at the core...

For instance, there wasn't an m4b entry in the mimetypes before, and there still isn't one.

From the logic flow of COPS, this is roughly what happens:
1. you navigate to a page where you get a list of books from Calibre\BookList - no restriction on format
For example for PageRecentBooks:
https://github.com/mikespub-org/seblucas-cops/blob/a6d3e663748a12fc9a46ece04d29b96b4ba6e4f0/lib/Pages/PageRecentBooks.php#L36
3. for each of the books, we create a book instance in Calibre\Book - no restriction on format
https://github.com/mikespub-org/seblucas-cops/blob/a6d3e663748a12fc9a46ece04d29b96b4ba6e4f0/lib/Calibre/BookList.php#L414
4. for each book instance, we get the entry to send back via JSON - no restriction on format
https://github.com/mikespub-org/seblucas-cops/blob/a6d3e663748a12fc9a46ece04d29b96b4ba6e4f0/lib/Calibre/BookList.php#L415
6. for each book entry, get a link array with the authors, series and data (=actual files) by book in Calibre\Book
https://github.com/mikespub-org/seblucas-cops/blob/a6d3e663748a12fc9a46ece04d29b96b4ba6e4f0/lib/Calibre/Book.php#L523
   - only the $config['cops_ignored_formats'] are ignored in the database lookup in Calibre\Book
Book->getDatas() goes to Book->getDataByBook()
https://github.com/mikespub-org/seblucas-cops/blob/a6d3e663748a12fc9a46ece04d29b96b4ba6e4f0/lib/Calibre/Book.php#L647
   - but then we check if the data is a known type in Calibre\Data
https://github.com/mikespub-org/seblucas-cops/blob/a6d3e663748a12fc9a46ece04d29b96b4ba6e4f0/lib/Calibre/Book.php#L541

Here it gets tricky, because we check the format (extension) against the mimetypes.
https://github.com/mikespub-org/seblucas-cops/blob/a6d3e663748a12fc9a46ece04d29b96b4ba6e4f0/lib/Calibre/Data.php#L112

Are you sure you didn't have a customized mimetypes table with 'm4b' added, or does the Calibre database contain 'M4A' for the format field of the data table?

```
$ sqlite3 metadata.db
sqlite> select id, book, format, name from data;
1|2|EPUB|The Return of Sherlock Holmes - Arthur Conan Doyle
2|3|EPUB|The Casebook of Sherlock Holmes - Arthur Conan Doyle
...
sqlite> .quit
```
Is this something you could check? Do we actually get a link for the m4b file at this point or not?

Because the next step is in JSON renderer (HTML page) or OPDS renderer (OPDS feed), where we do some more processing of the formats:

5. in OPDS renderer, for each book entry, render the links found in step 4 - no change compared to before
https://github.com/mikespub-org/seblucas-cops/blob/a6d3e663748a12fc9a46ece04d29b96b4ba6e4f0/lib/Output/OPDS_renderer.php#L284
5. in JSON renderer, for each book entry, go through the list of $config['cops_preferred_formats'] and get the data for the first 2 ones it finds
https://github.com/mikespub-org/seblucas-cops/blob/a6d3e663748a12fc9a46ece04d29b96b4ba6e4f0/lib/Output/JSON_renderer.php#L37
  - if 'M4A' (or whatever above) is not in your config_local.php then it won't show up...

When you go to an individual book in the HTML page, the logic flow is slightly different, and the filtering of formats at well. 
There you should get a link to all data formats it found in step 4.a. above, regardless of the extension.
https://github.com/mikespub-org/seblucas-cops/blob/a6d3e663748a12fc9a46ece04d29b96b4ba6e4f0/lib/Output/JSON_renderer.php#L127

And yes, all this has been a bit of a mess even in seblucas' version :-)

_Originally posted by @mikespub in https://github.com/mikespub-org/seblucas-cops/issues/27#issuecomment-1708142479_

**Comment by Chirishman** [comment]
Well it's not working anymore when I revert the linuxserver docker image to `33c50831617848bc4ed714633a988404031971673efb68f094972dbfb28c57ae` but keep my current config file and folder layout so maybe it working before was related to my previous non-standard folder structure.

Either way the web browser version of Calibre appears to offer the format: 
<img width="406" alt="image" src="https://github.com/mikespub-org/seblucas-cops/assets/7658840/e9cfcd51-c070-428e-93a1-b9960b8f3e2b">
and downloading from the web view works on the most recent release with my current config file, so it's only OPDS where this is broken.

**Comment by mikespub** [comment]
Thanks for sharing the screen recording, but since I don't know what it's supposed to look like (other than not jumping over & over), it doesn't really tell me much.

Could you in your browser navigate to the same list of books, and then replace the "index.php" in the URL with "feed.php" but keep the URL parameters? That should show you the OPDS feed in XML format that your e-reader chokes on - I'm looking for what the link (if any) looks like for that book in m4b format.

**Comment by Chirishman** [comment]
OK so I've spent a lot of time staring into this code now for as little PHP knowledge as I have and I think I may have identified why this is handled differently between `OPDS_renderer.php` and `JSON_renderer.php`

I found this by looking at the generated HTML and XML and following the `OPDS_ACQUISITION_TYPE = "http://opds-spec.org/acquisition"` breadcrumbs since that is used inside of the link tags in OPDS xml output but not in JSON/web view and tracing places where that was used.

To start with I think the issue comes down to this check in the definition of `getLinkArray()` in `book.php` which excludes anything that isn't a known type on line 541

https://github.com/mikespub-org/seblucas-cops/blob/a6d3e663748a12fc9a46ece04d29b96b4ba6e4f0/lib/Calibre/Book.php#L523-L560

A call to which is part of the definition of `getEntry()` here on line 573
https://github.com/mikespub-org/seblucas-cops/blob/a6d3e663748a12fc9a46ece04d29b96b4ba6e4f0/lib/Calibre/Book.php#L566-L576

which is called by `getEntryArray()` here on line 415

https://github.com/mikespub-org/seblucas-cops/blob/a6d3e663748a12fc9a46ece04d29b96b4ba6e4f0/lib/Calibre/BookList.php#L390-L418

I haven't fully traced out how that feeds to the OPDS side yet but I *have* identified that `JSON_renderer.php` explicitly calls **a completely different function with the exact same name** (🤦‍♂️) out of `filter.php`
https://github.com/mikespub-org/seblucas-cops/blob/a6d3e663748a12fc9a46ece04d29b96b4ba6e4f0/lib/Output/JSON_renderer.php#L418
which is defined here:
https://github.com/mikespub-org/seblucas-cops/blob/a6d3e663748a12fc9a46ece04d29b96b4ba6e4f0/lib/Calibre/Filter.php#L363-L394

This version of the function does not do any checking for known types as far as I can tell.

**Comment by mikespub** [comment]
Actually the Filter:: function you're referring to here is only used to fill the 'filters' - it's not relevant to which books are shown with which formats, as I described in the logic flow above.

But yes, knowing which format Calibre actually stores in the database ('M4A', 'M4B', ...) is important to know if we need to adapt mimetypes, so that the ifKnownTypes() will still work.

**Comment by mikespub** [comment]
Thanks, that helps clarify things a lot. I see from the HTML that it's indeed "m4b" that is identified as the type, so after adding m4b in the mimetypes as I did, you should already be able to navigate to that book in OPDS again.

As for why the e-reader crashes when there's no valid acquisition link in the entry, that's another matter. I can indeed filter out entries with no valid formats on COPS side, but you might want to let the developer of the client app (or other users) know about this issue too...

Thanks again for all the tracing...

**Comment by Chirishman** [comment]
> As for why the e-reader crashes when there's no valid acquisition link in the entry, that's another matter. I can indeed filter out entries with no valid formats on COPS side, but you might want to let the developer of the client app (or other users) know about this issue too...

Yeah, it's pretty unfortunate that all of the good OPDS readers for iOS seem to be literal abandonware.

- Kybook 3 hasn't seen an update since February of 2019
- Marvin 3 hadn't seen an update since October of 2017 and got unpublished form the app store earlier this year

Everything new I've tried doesn't really do what I need it to do in terms of organization and support for both OPDS and TTS.

**Comment by mikespub** [comment]
I'm not an iOS user myself, but what about any of Readium-based clients listed at https://github.com/readium/awesome-readium ?

**Comment by Chirishman** [comment]
That's a good thought, it's probably worth exploring those again.

I checked the items on that list out in 2021 when I first found Thorium and started using it on desktop. At that point there weren't very many entries on the list and the ones that did exist where specifically built for some public library system somewhere that I don't live (like [Biblio](https://apps.apple.com/us/app/biblio-library)) or were otherwise implemented to provide access to single service (like [Bookbeat](https://apps.apple.com/us/app/id1056652614))

Anyway, not general-use ebook readers.

The list looks to have more than doubled now though, maybe there's something I can use in there now!

**Comment by Chirishman** [comment]
Well there goes three hours of my life I'm not getting back.

My findings on the 33 mobile apps listed in that document:

| **#** | **Finding**                                    |
|-------|------------------------------------------------|
| 16    | Locked to a specific Ebook Vendor              |
| 14    | Locked to one or more specific Library Systems |
| 3     | Actually a general use ebook reader (on paper)            |

Of the ones that are actual ebook readers (allegedly) for general usage only one can be pointed at an OPDS feed that isn't already baked in.

**Aldiko Next**

Good:
- This is the only one of these that's actually competent!
- You can actually point it at your own OPDS feeds or any OPDS feed you want!
- If you don't care about/use TTS stop reading here! You've found your new ebook reader app!
- TTS uses the iOS native TTS engine and respects your global pronuciation settings which is great!
- TTS can be paused and resumed! You can skip back and forward a sentence if you missed something!

Bad:
- Unfortunately whenever you begin TTS it will **only start at the beginning of a chapter** and you can **only skip ahead one sentence at a time**. If you had been near the end of a chapter when you closed the app RIP you.
- It pauses for a really long time, somewhere between 1.5 and 2 full seconds after every sentence *no matter what playback speed you have the TTS set to*. Unlistenable, especially if you listen at high speeds.

The two which only support baked-in OPDS feeds also have other problems:

**Baobab**

- Supports manually adding books but **only supports baked in OPDS feeds from select participating libraries**. Included in this category because unlike the other library-locked apps it doesn't block you from *manually* adding books.
- TTS does not use or iOS' built in TTS engine/settings/pronunciation corrections and has no inbuilt support for pronunciation correction. Also has **no pause and resume** support, only full stop after which it **always starts again at the very first sentence of the book**. Worse than useless.

**DITA Reader**

This one is hilarious. According to the description this us supposed to be a normal ebook reader for anyone to use. In reality this app is published for an audience of 1, mister Aferdita Muriqui himself. He put his personal gmail in for the support email on the google play app 🤣

Just a few of the problems:

- Does not support manually adding books/the Open With command cannot be used to open a book using it
- Has a hardcoded OPDS mapping for "Afurdita's Collection" which includes several books which I'm pretty certain he does not have a license to legally redistribute.
- Does not suport YOUR PHONE'S OS being in dark mode. Not just that the app doesn't have it's own dark mode, if your PHONE is in dark mode then the whole app is white text on a white background.
- If you click the "My Books" navigation at the bottom it doesn't say "My Books" at the top of the page it takes you to, it says "Aferdita's books"

This one is clownshoes and I'm going to email the authors of the seven copyrighted books he's serving and ask if he got their permission given that they all seem to be listed on Kindle for between $5 and $10

I'm honestly kinda shocked, that's not usually the kind of thing you can get away with on the Apple App Store.

And I'm 0/33 for Kybook 3 alternatives for iOS still 😕

**Comment by mikespub** [comment]
Thanks for the update Chirishman - we all contribute in our own way, and at least I can point to your analysis next time someone asks me for a recommendation :-)

I'm a bit surprised at the result though - Thorium Reader gave me a good impression of the whole Readium thing, but I guess that's an exception compared to the other tools then, unfortunately...

**Comment by Chirishman** [comment]
Yeah it surprised me too, Thorium is my desktop go-to nowadays but I think it comes down to the fact that they don't publish a Thorium equivalent for mobile, only a codebase for rolling such a thing and other people build the apps.

The actual codebase seems fine, it's just a matter of who is implementing it and most of the people in the market for such are going to be libraries and people looking to sell DRMed ebooks.

The frustrating part to me is that some of the library-maintained ones look like they'd be pretty good but you can't bring your own books and they don't function at all unless you log into them with a library account first.

It's sad that the overall results for me are the same as they were two years ago.

**Comment by Chirishman** [comment]
> Thanks for the update Chirishman - we all contribute in our own way, and at least I can point to your analysis next time someone asks me for a recommendation :-)

Yeah here's a spreadsheet with my individual breakdowns about each of the 33 apps in case anyone comes later and is curious:
https://docs.google.com/spreadsheets/d/1Ua2S9im5kxwJhOxowJaPgbP8s9JOcGCKL6BF4kVS8sE/edit?usp=sharing

**Comment by mikespub** [comment]
Nice :-) Have you had a look at PocketBook Reader maybe?

I haven't played much with it, but on Android it allows me to add my own COPS sites as OPDS feeds. No idea about the quality of TTS though...

**Comment by Chirishman** [comment]
I honestly hadn't purely because the icon and name were both similar to an very bad app that I tried a long time ago on a Windows RT surface tablet but looking at them more closely I don't think there's any connection.

Verdict: Seems pretty OK! TTS is 4/10

- Uses iOS built in engine (and thus reflects pronunciation fixes made in the main OS settings menu)
- No buttons to skip back or forward
- Does support pause-resume
- Can highlight a point in the page and have it start reading from where you selected (like you can in Kybook)
- Unfortunately has the same problem as **Aldiko Next** of seemingly having a hard coded pause duration between sentences that does not adjust along with the speaking/playback rate. Not _quite_ as bad as it is in **Aldiko Next** but I'm definitely not switching from Kybook 3 to this unless I have no other choice. If you listen at 1-1.5x speed you might be fine.

Unfortunately I'm the kind of lunatic that listens to audiobooks and podcasts at 3.5 speeds and tts at whatever max speed the settings will suffer. I know I'm kind of an edge case.

I also don't like being asked for push notification permissions and if I'd like "special offers" right away when I first open the app, that's not a good tone-setter.

Fiddling with it a bit more think if I daily-drove it I'd get really annoyed that the OPDS feeds are kind of buried several interactions deep. They're not on the home screen and you have to go to books and then, because it's wrapped off the side of the screen, you have to swipe all the way to the right past a bunch of icons I'll never use for Dropbox and Google Drive, and _then_ select the OPDS library you actually want once you're in it.

If you could reorder the list so OPDS comes first or hide icons you don't want I could live with it but it would still be a massive quality of life setback from Kybook which lets you pin both OPDS libraries and even *shortcuts* to specific points in the library to your home screen.

I've got quick shortcuts to the **Recently Added** categories in a few of my libraries on the home screen that shows up when you make a new tab right now above the entry for my whole instance:
![IMG_8197](https://github.com/mikespub-org/seblucas-cops/assets/7658840/69028996-77b0-417b-a4d7-2cccad1ef9a9)

They navigate directly to `http://mycopsservername:8080/feed.php?page=10&db=3` and `http://mycopsservername:8080/feed.php?page=10&db=4`

They're not hard to create either, the action to add them is part of the context menu when you're browsing any particular point in the feed.

**Comment by Chirishman** [comment]
Oh, other things I've tried that didn't work and why:

**Bookfusion**
- Would be a replacement for using OPDS since it doesn't support it but has it's own integration extension for Calibre, not a huge ask, also promises to support place-tracking
- Doesn't have any handling/support for updating the cloud/synced version of an ebook if it is edited and more chapters are added so it's straight up not usable for serially published stories like Webfiction and Fanfiction which are my highest turnover files.
- They seem to actually be in the Cloud Storage business unfortunately. To use their app/service you have to store your books in their cloud and their max storage cap on the most expensive plan only gives you 100gb of storage. Forgetting my normal literature ebook library for the moment because it's not easy for me to measure the size of it without including the associated audiobooks just my Comics, Manga, Fanfiction and Webfiction libraries come to 544gb so it's a non-starter. If they had a bring-your-own-cloud-storage tier that supported running the whole library live out of NextCloud or Dropbox or something there might be room for a conversation.

**Speechify**
- AI TTS Voices are legitimately impressive! At least what I can sample of them without paying seems to be.
- Free version **using the iOS native TTS engine** demands that you pay them **$140/year billed annualy** to increase the speed above 1.1x
- You get other things like the premium AI voices for that price but paywalling access to functionality made up entirely of the phone's native OS accessibility features is a scumbag move.
- No OPDS support
- Claims to support EPUB, various formats.
- Actually converts all ingested files into flat PDFs with no navigation/TOC/index.

Even though the AI voices are incredibly impressive, between the scumbag tactics in the free mode, the PDF conversion, and the streaming-service scale subscription cost put this firmly in the "no" bucket for me.

It did start me down a rabbithole of exploring TensorFlowTTS speech synthesis to explore doing my own AI TTS on one of my home servers though so there is that.

**Comment by dunxd** [comment]
This last few bits of discussion would be good moved into the discussion area, as once this ticket is closed people won't see it. The research by @Chirishman on iOS eReaders is super valuable!

From an Android perspective I am liking Librera for OPDS/browser library support. Haven't tried with TTS - I really don't want to hear the Google Maps lady reading books to me which I suspect would be the Android experience.

**Comment by Chirishman** [comment]
> This last few bits of discussion would be good moved into the discussion area, as once this ticket is closed people won't see it. The research by @Chirishman on iOS eReaders is super valuable!

Yeah I think I might write it up for a [tech blog](https://blog.chiriserv.org/) post and I'll link it in the discussion for this repo when I do. It's been like 4 years since my last post there which was on authoring M4B audiobooks...

> From an Android perspective I am liking Librera for OPDS/browser library support. Haven't tried with TTS - I really don't want to hear the Google Maps lady reading books to me which I suspect would be the Android experience.

I hear good things about **Moon+ Reader** for Android personally. As for TTS I bet you'd be surprised, Modern versions of mobile OSes usually have extra enhanced voice packs that sound better which are optional downloads in the accessibility settings because blind/visually impaired people are a part of the smartphone market too.
