### ISSUE TITLE
No large book covers and white screen with vienwer

### ISSUE THREAD

**Issue by marioscube** [mikespub-org/seblucas-cops#73]
Running:
- Debian 12 Bookworm
- PHP 8.2.7
- browser firefox
- COPS version 2.2.1 downloaded from github (this site)
- **classic COPS interface**
- 3 COPS libraries

Error 1:
- when selecting a book cover, I used to see the book cover in large format and was able to scroll horizontally through all covers.
- now I do not see any large cover

Error 2
- selecting view icon only works for the fist (0) library. It does not work for other libraries (1) and (2). I only see a white screen.

Am I doing something wrong?

**Comment by mikespub** [comment]
There was an error for multi-database that should be fixed in the latest release 2.2.2, but that was only for epub reader and email.

I'm not sure I understand the errors you mentioned here - what did you mean by selecting a book cover and scroll horizontally for Error 1, and what did you mean by "selecting view icon" only for Error 2?

**Comment by marioscube** [comment]
I will install version 2.2.2 tomorrow and report back.

I like to fix 1 error at a time ;-)

**Comment by marioscube** [comment]
@mikespub 
**Error 2** is resolved! Thank you!

**Error 1** (additional explanation):

In the legacy COPS I could click on a cover in this view:
![Screenshot 2024-02-19 at 11 54 29](https://github.com/mikespub-org/seblucas-cops/assets/20281601/9c7c7bb3-6182-4ac0-a735-ec8779235cbc)
 and get this screen with large covers (note the triangles on both sides). In this screen I could scroll horizontally through all covers. I think this is a handy feature.
![Screenshot 2024-02-19 at 11 57 30](https://github.com/mikespub-org/seblucas-cops/assets/20281601/8c7085d9-2d46-4e74-a264-16ef78040ec5)

Selecting a book goes through clicking on the title (not on the cover/icon).

I like my old COPS back ;-)

Keep up the great work!!!

**Comment by mikespub** [comment]
Hi @marioscube - about Error 1 that's what I thought you meant, and it's a nice feature indeed :-)

But here's my problem: in the original COPS code at https://github.com/seblucas/cops and further releases here at https://github.com/mikespub-org/seblucas-cops there is **no** code, template or javascript that supports this...

Can you find out which version you were based on, and if there was anything customized after this version from elsewhere, so that I can recreate this?

Thanks

**Comment by marioscube** [comment]
@mikespub 

In this version it still worked:
![Screenshot 2024-02-19 at 13 18 44](https://github.com/mikespub-org/seblucas-cops/assets/20281601/eab597c5-a0fe-4c53-a8f7-23b37640b47d)

**Comment by marioscube** [comment]
@mikespub 

Changes in ../cops/templates/default/main.html and or ../cops/templates/default/bookdetail.html seem to be the cause.

**Comment by mikespub** [comment]
Aha, we're getting closer - between 1.4.2 and 1.4.3 I did indeed switch the link on the thumbnail image in the main.html template from coverURL (fetch.php?id=...) to detailURL (index.php?page=13&id=...), because ...  in the main navigation it made more sense to point to the detail page and it seemed pointless to link to a cover image by itself.

Of course, at that point I did **not** have that functionality with previous & next buttons in the interface that you showed here either - so I still don't know if & when that actually disappeared.

Did you have any other customization of templates or javascript by any chance, or do you still have this working with 1.4.2?

**Comment by marioscube** [comment]
@mikespub 

That functionality has been in COPS since almost forever.

If I, just for testing purposes, copy the html files from version 1.4 to version 2.2 this works again.
I might then be missing out on new functionality though.

**Comment by mikespub** [comment]
Thanks for the clarifications & screenshots. When trying to reproduce this, I noticed that you used the "Lightbox" option (magnific popup) for the default template, which actually still works for 2.2.2+ when it gets the right cover url - now fixed with the changes above :-)

**Comment by marioscube** [comment]
@mikespub 

I have my old COPS back, now working with php8.

Thank you!

Issue closed!
