### ISSUE TITLE
Problems with "Full URL prefix"

### ISSUE THREAD

**Issue by marioscube** [mikespub-org/seblucas-cops#75]
* Full URL prefix (with trailing /)
 * useful especially for Opensearch where a full URL is often required
 * For example Mantano, Aldiko and Marvin require it.
$config['cops_full_url'] = 'http://192.168.1.xxx/cops/';

Used to work with:

- http://localhost/cops
- http://DomainName/cops

Now only http://192.168.1.xxx/cops/ works. :-(

I hardly ever use Opensearch with Marvin but .......

**Comment by mikespub** [comment]
Hi @marioscube are you saying you **don't** want to use `cops_full_url` except for opensearch with Marvin?

That's not quite how it works these days I'm afraid, as all generated URLs are now prefixed with `cops_full_url`. So your best bet might be to use:
```
$config['cops_full_url'] = '/cops/';
```
without the http://hostname part so that localhost and DomainName will keep being used.

That only leaves Opensearch on Marvin as a potential problem, and that might already work fine just with the /cops/ part - can you check it out?

Note: with the hostname included, the initial page load with http://localhost/cops/ or http://DomainName/cops/ could still work too, but you may get some browser restrictions on script origin etc.

**Comment by mikespub** [comment]
And if Marvin doesn't work, I'd probably use something like this in your `config_local.php`

```
if (preg_match('/Marvin/', $_SERVER['HTTP_USER_AGENT'])) {
    $config['cops_full_url'] = 'http://192.168.1.xxx/cops/';
} else {
    $config['cops_full_url'] = '/cops/';
}
```
That way everyone is happy :-)

**Comment by mikespub** [comment]
Excellent news, and thanks for the feedback

**Comment by mikespub** [comment]
Clarified use of cops_full_url + reporting javascript errors instead of white screen for visibility
